/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package BurgerPackage;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class SearchBestCustomerForm extends javax.swing.JFrame {
    
        
    private BurgerList burgerList;
    /**
     * Creates new form BurgerMainForm
     */
    public SearchBestCustomerForm(BurgerList burgerList) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Search Best Customer");
        this.burgerList=burgerList;
        
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBestCustomer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(204, 0, 51));
        label1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Search Best Customers");

        btnExit.setBackground(new java.awt.Color(204, 0, 51));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tblBestCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Total"
            }
        ));
        tblBestCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblBestCustomerFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tblBestCustomer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblBestCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblBestCustomerFocusGained
        BurgerList burgerList = BurgerController.importBurgers();
        BurgerList newList = new BurgerList();
         
        for (int i = 0; i < burgerList.size(); i++) {
             Burger burger = burgerList.get(i);
             
             boolean isDuplicate = false;
             for (int j = 0; j < newList.size(); j++) {
                
                    Burger newBurger = newList.get(j); 
                 if(burger.getCustomerId().equals(newBurger.getCustomerId())){ 
                    
                     isDuplicate = true;
                     break;
                 }
             }
             if(!isDuplicate){
                 newList.add(burger);
             }
        }
       
        
        
        BurgerList quList = new BurgerList();
        
        for (int i = 0; i <newList.size(); i++) {
                Burger newBurger = newList.get(i); 
                int total = 0;
            for (int j = 0; j < burgerList.size(); j++) {
                 Burger burger = burgerList.get(j);
                if(newBurger.getCustomerId().equals(burger.getCustomerId())){
                    total+=burger.getOrderQty();
                }
                
            }
             Burger tempBurger = new Burger(
                     newBurger.getOrderId(),
                  newBurger.getCustomerId(),
                 newBurger.getCustomerName(),
                    total,
                           newBurger.getOrderStatus()
                     
            );
             
             quList.add(tempBurger);
            
        }
        
         
         for (int i = 0; i < quList.size()-1; i++) {
             for (int j = 0; j < quList.size()-i-1; j++) {
                 Burger current = quList.get(j);
                 Burger next = quList.get(j+1);
                 
                 if(current.getOrderQty()<next.getOrderQty()){
                     
                     quList.remove(j);
                     quList.add(j,next);
                     quList.remove(j+1);
                     quList.add(j+1,current);
                     
                 }
             }
        }
         
         DefaultTableModel dtm = (DefaultTableModel) tblBestCustomer.getModel();
         dtm.setRowCount(0);
          
        for (int i = 0; i < quList.size(); i++) {
            Burger burger = quList.get(i);
          
            Object[] rowData={burger.getCustomerId(),burger.getCustomerName(),burger.getOrderQty()*Burger.burgerPrice};
            dtm.addRow(rowData);
        }
       
    
    
    }//GEN-LAST:event_tblBestCustomerFocusGained


  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTable tblBestCustomer;
    // End of variables declaration//GEN-END:variables
}
